<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmkDoc.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmkDoc.Application\SmkDoc.Application.csproj" />
    <ProjectReference Include="..\SmkDoc.Domain\SmkDoc.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Handlebars.Net" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" />
    <PackageReference Include="Minio" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

</Project>
